// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Y1dXaW5OkpZiVdNSsFXPG7qQQEN9vFA',
    appId: '1:1010364828673:android:ae94ea419f1df3bede8400',
    messagingSenderId: '1010364828673',
    projectId: 'zyncro-f5fdd',
    storageBucket: 'zyncro-f5fdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFUAlfIcAjUEpcpm4wravllu1qLCS2BGQ',
    appId: '1:1010364828673:ios:a17e6a988445c784de8400',
    messagingSenderId: '1010364828673',
    projectId: 'zyncro-f5fdd',
    storageBucket: 'zyncro-f5fdd.firebasestorage.app',
    androidClientId: '1010364828673-k9lojka7iuma77g152hhceoem2216vuo.apps.googleusercontent.com',
    iosClientId: '1010364828673-8v4bp0cr6dtatbmqi0drm0qf1e9nil5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.zyncro',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmfKVwX1ubPW3fVinZ8iw8to5YngCs-yw',
    appId: '1:1010364828673:web:49009c1e5b255367de8400',
    messagingSenderId: '1010364828673',
    projectId: 'zyncro-f5fdd',
    authDomain: 'zyncro-f5fdd.firebaseapp.com',
    storageBucket: 'zyncro-f5fdd.firebasestorage.app',
    measurementId: 'G-2HLBMQ0NC2',
  );

}