// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARKMKHqBRDDVZu5s_xy2kQiz-4CfoOFYM',
    appId: '1:139952548131:web:92ef8de53d3648a27e4496',
    messagingSenderId: '139952548131',
    projectId: 'zyncro-app',
    authDomain: 'zyncro-app.firebaseapp.com',
    storageBucket: 'zyncro-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtLH4l1mvFxg4chEXshVNPHH0CQw9W3hA',
    appId: '1:1010364828673:android:ae94ea419f1df3bede8400',
    messagingSenderId: '1010364828673',
    projectId: 'zyncro-f5fdd',
    storageBucket: 'zyncro-f5fdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Lc37n95t9w4gaGcvqaRTF4OzO1q1WQI',
    appId: '1:1010364828673:ios:a17e6a988445c784de8400',
    messagingSenderId: '1010364828673',
    projectId: 'zyncro-f5fdd',
    storageBucket: 'zyncro-f5fdd.firebasestorage.app',
    iosBundleId: 'com.example.zyncro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg3UXVYzXSbP2MTcG3ygK-dKIFKyWK5Sg',
    appId: '1:139952548131:ios:83a8ff30e8716ae67e4496',
    messagingSenderId: '139952548131',
    projectId: 'zyncro-app',
    storageBucket: 'zyncro-app.firebasestorage.app',
    iosBundleId: 'com.example.zyncro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARKMKHqBRDDVZu5s_xy2kQiz-4CfoOFYM',
    appId: '1:139952548131:web:74caec54074dfd1d7e4496',
    messagingSenderId: '139952548131',
    projectId: 'zyncro-app',
    authDomain: 'zyncro-app.firebaseapp.com',
    storageBucket: 'zyncro-app.firebasestorage.app',
  );
}